import PDFDocument from 'pdfkit'

export const generateReceiptPDF = (res, data) => {
  const {
    receipt_number, payment_date, tenant_name, tenant_phone,
    landlord_name, landlord_phone, property_title, property_location,
    amount, method, month_year, rental_start, notes
  } = data

  const doc = new PDFDocument({ margin: 50, size: 'A4' })

  res.setHeader('Content-Type', 'application/pdf')
  res.setHeader('Content-Disposition', `attachment; filename=receipt-${receipt_number}.pdf`)
  doc.pipe(res)

  // Header background
  doc.rect(0, 0, 595, 120).fill('#1d4ed8')

  doc.fill('white')
    .fontSize(24)
    .font('Helvetica-Bold')
    .text('Smart Rental RW', 50, 35)

  doc.fontSize(11)
    .font('Helvetica')
    .text('Rental Management System — Rwanda', 50, 65)
    .text('www.smartrental.rw | info@smartrental.rw', 50, 82)

  doc.fontSize(14)
    .font('Helvetica-Bold')
    .text('RENT RECEIPT', 400, 45, { align: 'right' })

  doc.fontSize(10)
    .font('Helvetica')
    .text(`Receipt #: ${receipt_number}`, 400, 68, { align: 'right' })
    .text(`Date: ${payment_date}`, 400, 84, { align: 'right' })

  // Paid badge
  doc.rect(50, 135, 120, 28).fill('#22c55e')
  doc.fill('white')
    .fontSize(12)
    .font('Helvetica-Bold')
    .text('✓  PAID', 68, 143)

  // Divider
  doc.moveTo(50, 175).lineTo(545, 175).stroke('#e5e7eb')

  // Tenant details
  doc.fill('#111827')
    .fontSize(10)
    .font('Helvetica-Bold')
    .text('TENANT DETAILS', 50, 190)

  doc.font('Helvetica')
    .fill('#374151')
    .fontSize(10)
    .text(`Name: ${tenant_name}`, 50, 208)
    .text(`Phone: ${tenant_phone}`, 50, 223)

  // Landlord details
  doc.fill('#111827')
    .fontSize(10)
    .font('Helvetica-Bold')
    .text('LANDLORD DETAILS', 320, 190)

  doc.font('Helvetica')
    .fill('#374151')
    .fontSize(10)
    .text(`Name: ${landlord_name}`, 320, 208)
    .text(`Phone: ${landlord_phone}`, 320, 223)

  // Divider
  doc.moveTo(50, 248).lineTo(545, 248).stroke('#e5e7eb')

  // Property details
  doc.fill('#111827')
    .fontSize(10)
    .font('Helvetica-Bold')
    .text('PROPERTY DETAILS', 50, 263)

  doc.font('Helvetica')
    .fill('#374151')
    .fontSize(10)
    .text(`Property: ${property_title}`, 50, 281)
    .text(`Location: ${property_location}`, 50, 296)
    .text(`Rental Period: ${month_year}`, 50, 311)
    .text(`Agreement Start: ${rental_start}`, 50, 326)

  // Divider
  doc.moveTo(50, 350).lineTo(545, 350).stroke('#e5e7eb')

  // Payment details
  doc.fill('#111827')
    .fontSize(10)
    .font('Helvetica-Bold')
    .text('PAYMENT DETAILS', 50, 365)

  // Table header
  doc.rect(50, 385, 495, 28).fill('#f3f4f6')
  doc.fill('#374151')
    .fontSize(9)
    .font('Helvetica-Bold')
    .text('DESCRIPTION', 60, 394)
    .text('PERIOD', 220, 394)
    .text('METHOD', 340, 394)
    .text('AMOUNT', 450, 394)

  // Table row
  doc.rect(50, 413, 495, 32).fill('white').stroke('#e5e7eb')
  doc.fill('#111827')
    .fontSize(10)
    .font('Helvetica')
    .text('Monthly Rent', 60, 423)
    .text(month_year, 220, 423)
    .text(method.replace('_', ' ').toUpperCase(), 340, 423)

  doc.fill('#1d4ed8')
    .font('Helvetica-Bold')
    .fontSize(11)
    .text(`RWF ${parseInt(amount).toLocaleString()}`, 450, 423)

  // Total row
  doc.rect(50, 445, 495, 36).fill('#1d4ed8')
  doc.fill('white')
    .fontSize(12)
    .font('Helvetica-Bold')
    .text('TOTAL PAID', 60, 457)
    .text(`RWF ${parseInt(amount).toLocaleString()}`, 450, 457)

  // Notes
  if (notes) {
    doc.fill('#374151')
      .fontSize(9)
      .font('Helvetica')
      .text(`Notes: ${notes}`, 50, 498)
  }

  // Footer divider
  doc.moveTo(50, 520).lineTo(545, 520).stroke('#e5e7eb')

  doc.fill('#6b7280')
    .fontSize(9)
    .font('Helvetica')
    .text('This is an official rent receipt generated by Smart Rental RW system.', 50, 535, { align: 'center' })
    .text('For any queries, contact your landlord or visit www.smartrental.rw', 50, 550, { align: 'center' })

  // Signature lines
  doc.moveTo(350, 620).lineTo(545, 620).stroke('#9ca3af')
  doc.fill('#6b7280')
    .fontSize(9)
    .text('Landlord Signature', 380, 628)

  doc.moveTo(50, 620).lineTo(245, 620).stroke('#9ca3af')
  doc.fill('#6b7280')
    .fontSize(9)
    .text('Tenant Signature', 85, 628)

  doc.fill('#9ca3af')
    .fontSize(8)
    .text(
      `Generated on ${new Date().toLocaleDateString('en-RW')} by Smart Rental RW`,
      50, 760, { align: 'center' }
    )

  doc.end()
}